SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BARREL_LADDER_ODDS = 35
COLLISION_MARGIN = 5

STATUS_JUMPING = 0
STATUS_DYING = 1
STATUS_WALKING = 2

DEATH_DURATION = 0.5
JUMP_DURATION = 17

#PLATFORM_HEIGHT = 25