SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BARREL_LADDER_ODDS = 35
COLLISION_MARGIN = 5

MOVE_DISTANCE = 2

STATUS_JUMPING = 0
STATUS_DYING = 1
STATUS_WALKING = 2

PLATFORM_HEIGHT = 20

DEATH_DURATION = 0.5
JUMP_DURATION = 17

JUMPMAN_JUMP_BOOST = 150

JUMPMAN_VERT_ACCELERATION = 200
JUMPMAN_MAX_VERT_VEL = 150

#PLATFORM_HEIGHT = 25